name: Deploy Angular Frontend to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli@17

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install --legacy-peer-deps

      - name: Build Angular application
        working-directory: ./frontend
        run: ng build --configuration production --base-href /test/
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist/angular-frontend
          cname: false
